name: GA test
on:
    push:
      branches: dev
env:
  var: test variable

jobs:
 build_job:
  runs-on: ubuntu-latets
  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
          java-version: '17'
          distribution: 'temurin'
          overwrite-settings: false
    - name: Build with Maven
      run: mvn clean install